/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_window1y (void);
GtkWidget* create_window2y (void);
GtkWidget* create_window3y (void);
GtkWidget* create_window4y (void);
GtkWidget* create_window5y (void);
GtkWidget* create_window6y (void);
GtkWidget* create_windowsirinegestionouvrier (void);
GtkWidget* create_window1sir (void);
GtkWidget* create_windowajouterouvrier (void);
GtkWidget* create_windowrechercherouvrier (void);
GtkWidget* create_windowmodificationsirine (void);
GtkWidget* create_window2sir (void);
GtkWidget* create_dialog5sir (void);
GtkWidget* create_windowmodificationsirinetree (void);
GtkWidget* create_dialog1sir (void);
GtkWidget* create_dialog2sir (void);
GtkWidget* create_dialog3sir (void);
GtkWidget* create_dialog4sir (void);
GtkWidget* create_windowmeilleurouvrier (void);
GtkWidget* create_yousseftache2 (void);
GtkWidget* create_mouna_ajouter_cap (void);
GtkWidget* create_mouna_gestion_cap (void);
GtkWidget* create_mouna_reference_modifier (void);
GtkWidget* create_mouna_partie2 (void);
GtkWidget* create_youssef_f0 (void);
GtkWidget* create_mouna_modifier_cap (void);
